### ISSUE TITLE
How to Integrate Autopricer With TF2 Autobot

### ISSUE THREAD

**Issue by propewpou** [jack-richards/bptf-autopricer#11]
hello, could you explain how to connect this autopricer to tf2autobot pls?

**Comment by jack-richards** [comment]
If you're running the autopricer on the same server as the trading bot (tf2 auto bot), as directed in the tf2autobot wiki you can simply add the pricers URL to the CUSTOM_PRICER_URL field: https://github.com/TF2Autobot/tf2autobot/wiki/Configuring-the-bot#custom-pricer-settings---only-for-advanced-users.

If you leave the autopricer port as its default (3456), the custom pricer URL should be: http://localhost:3456

You should leave the CUSTOM_PRICER_API_TOKEN field as its default, as this pricer is not secured by an API token (since it has been made with running local to the consumer application in mind).

**Comment by jack-richards** [comment]
### **Also for those of you looking to get this set-up with TF2AutoBot:**

If you're unfamiliar with terms like Socket.IO or API, don't worry! You can safely ignore those parts as TF2AutoBot handles most of that for you. Just ensure you've followed **all** the instructions in the README.md and the steps mentioned above.

If you'd like to add items to be priced by the pricer (which can then be sold by TF2AutoBot using its !add command), and you're running both the bot and the pricer on the same machine, you can edit the [item_list.json file](https://github.com/jack-richards/bptf-autopricer/blob/main/files/item_list.json). Follow the provided example within the file to format your entries correctly.
