### ISSUE TITLE
error: relation "listings" does not exist

### ISSUE THREAD

**Issue by Mo7TaRiF** [jack-richards/bptf-autopricer#14]
Hey, The app wasn't getting any updates for prices for a week and when I update it, I keep getting this error?
How can I solve it ?

![Screenshot (91)](https://github.com/jack-richards/bptf-autopricer/assets/16272383/740c40a0-99bd-401c-9c02-4e6923979ab9)

**Comment by jack-richards** [comment]
You haven't set up the database yet or at the very least the listings table. To do so, refer to the instructions here: https://github.com/jack-richards/bptf-autopricer?tab=readme-ov-file#requirements

I would recommend that you follow the INITALIZE_DB instructions instead of going with the second database set-up option.
