### ISSUE TITLE
GetSchemaItems endpoint retired from IEconItems, breaks the code

### ISSUE THREAD

**Issue by StrangePlay02** [jack-richards/bptf-autopricer#18]
As title suggests, I think the mentioned endpoint has been retired, and the code can no longer run. Unfortunately, I can't pinpoint where and what exactly to change. Appreciate any help, thanks! Here's part of the error message:

Update 29/11/2024: Ok not facing the issue anymore. Still, curious what this is about. Perhaps it would help others to resolve this..

    **data: "<html><head><title>Not Found</title></head><body><h1>Not Found</h1>Method 'GetSchemaItems' has been retired in interface 'IEconItems_440'</body></html>"**

**Comment by jack-richards** [comment]
The error might have been caused by Steam performing some maintenance on its APIs. Also, I recommend **regenerating** your Steam API key since it is meant to be private, and you have exposed it here.

Even if the endpoint were to be shut down, I rely upon tf2autobot/tf2-schema to get the tf2 schema, so the developers of tf2autobot would likely fix it before I would need to.
